/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.int_watch.conf,v 5.0 2002/04/20 07:30:13 hardaker Exp $
 */
#ifndef NSTAGENTSUBAGENTOBJECT_H
#define NSTAGENTSUBAGENTOBJECT_H

#ifndef NET_SNMP_AGENT_INCLUDES_H
#define NET_SNMP_AGENT_INCLUDES_H

#include <net-snmp/agent/mib_module_config.h>
#include <net-snmp/agent/agent_module_config.h>

#include <net-snmp/agent/snmp_agent.h>
#include <net-snmp/agent/snmp_vars.h>
#include <net-snmp/agent/ds_agent.h>
#include <net-snmp/agent/agent_handler.h>
#include <net-snmp/agent/agent_read_config.h>
#include <net-snmp/agent/agent_trap.h>
#include <net-snmp/agent/agent_handler.h>
#include <net-snmp/agent/all_helpers.h>
#include <net-snmp/agent/var_struct.h>

#endif

/*
 * function declarations
 */
void            init_nstAgentSubagentObject(void);

#endif                          /* NSTAGENTSUBAGENTOBJECT_H */
